services:

   # конфигурация для сервисов по умолчанию в *этом* файле
   _defaults:
      autowire: true      # Автоматически внедряет зависимости в ваши сервисы.
      autoconfigure: true # Автоматически регистрирует ваши сервисы как команды, подписчики событий и т.д.


   Maris\Symfony\OSRM\:
      resource: '../../src/'
      exclude: '../../src/{DependencyInjection,Model}'


   Maris\Symfony\OSRM\Service\OSRMDirectionsService:
